#!/usr/bin/env bash
#display the subdomain where it points

dig_to_subdomain() {
  dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 {print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 2 ]; 
  then
  dig_to_subdomain "$2.$1" "$2"
fi

if [ "$#" -eq 1 ]
  then
  dig_to_subdomain "www.$1" "www"
  dig_to_subdomain "lb-01.$1" "lb-01"
  dig_to_subdomain "web-01.$1" "web-01"
  dig_to_subdomain "web-02.$1" "web-02"
fi
