#!/usr/bin/env bash
#install nginx and config to redirct_me
sduo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

config_dirct_me="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo chmod +w /etc/nginx/sites-enabled/default
sudo -i "s/server_name _;/$config_dirct_me/" /etc/nginx/sites-enabled/default
echo "https://www.youtube.com/watch?v=QH2-TGUlwu4" | sudo tee /var/www/html/redirect_me

sudo service nginx restart
