#!/usr/bin/env bash
#install nginx and config to redirct_me
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo sed -i '/server_name _;/a \       \t add_headers X-Served-By: $hostname\n;' /etc/nginx/sites-enabled/default
sudo service nginx restart
