#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#echo "8.8.8.8 facebook.com" >> /etc/hosts
#facebook.com resolves to 8.8.8.8.

sudo sed -i "s/^127.0.0.1$/127.0.0.2/" /etc/hosts
sudo sed -i "s/^*facebook.com$/8.8.8.8 facebook.com/" /etc/hosts
