#!/usr/bin/env bash
#change owner for nginx
sudo service nginx stop
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

chown -R nginx:nginx /etc/nginx/
chmod 700 /etc/nginx/
sudo service nginx restart
